account/urls.py
from django.urls import path
from . import views

app_name='account'

urlpatterns=[
    path("",views.home,name='home'),
    path('login/',views.login,name='login'),
    path('dashboard/',views.dashboard,name="dashboard"),
]

campus/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('account.urls',namespace='account')),
    path('api/',include('account.api_urls'))
]

account/models.py
from django.db import models

# Create your models here.

account/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
def home(request):
    return render(request,'account/home.html')

def login(request):
    if request.method == "POST":
        username=request.POST.get('username')
        password=request.POST.get('password')
        print(username,password)
             
    return render(request,'account/login.html')

def dashboard(request):
    return render(request,'account/dashboard.html')

# Create your views here.

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Campus</title>
        <link rel="stylesheet" href= "{% static 'css/style.css'%}" >
</head>
<body>
    <div>
        <h1>Campus Management system</h1>
        <nav style="text-align-last: right;">
        <a href="{% url 'account:home' %}" style="color:white">Home</a>
        <a href="{% url 'account:dashboard' %}" style="color:white">Dashboard</a>
        <a href="{% url 'account:login' %}" style="color:white">Login</a>
    </nav>
    </div>
    
    <hr>
    {% block content %}
    {% endblock %}

    
</body>
</html>